name: TowerClans
version: '1.0b'
main: phrase.towerClans.Plugin
api-version: '1.18'
depend:
  - Vault
  - ProtocolLib
  - WorldEdit
  - WorldGuard
soft-depend:
  - PlaceholderAPI
commands:
  towerclans: {}
  clan: {}