name: TowerClans
version: '2.2.1'
main: phrase.towerclans.TowerClans
author: phrase
api-version: '1.16'
depend:
  - Vault
  - packetevents
  - WorldEdit
  - WorldGuard
  - PlaceholderAPI
commands:
  clan: { }