name: TowerClans
version: '1.6.5'
main: phrase.towerclans.TowerClans
author: phrase
api-version: '1.16'
depend:
  - Vault
  - ProtocolLib
  - WorldEdit
  - WorldGuard
  - PlaceholderAPI
commands:
  clan: { }